name: Search for TODOs

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  search-todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ripgrep
        run: sudo apt-get update && sudo apt-get install ripgrep -y

      - name: Search for TODOs
        run: |
          rg TODO | tee todos.txt

      - name: Append TODOs to README
        run: |
          START_MARKER="<!-- TODOs -->"
          END_MARKER="<!-- /TODOs -->"
          TODOS_CONTENT=$(cat todos.txt)
          sed -i "/${START_MARKER}/a ${TODOS_CONTENT//$'\n'/\\n}" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Add TODOs from Ripgrep"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}